networks:
  kafka-net:
    name: kafka-net
    driver: bridge

services:
  monitoring:
    container_name: monitoring
    networks:
      - kafka-net
    build:
      context: .
      dockerfile: Dockerfile